registre_homepage:
    path:     /
    defaults: { _controller: RegistreBundle:Defaut:index}

login:
    path: /login
    defaults: { _controller: RegistreBundle:User:login }
    
login_check:
    path: /login_check

logout:
    path: /logout
    
entrades_list:
    path: /taula
    defaults: { _controller: RegistreBundle:Cdr:entrades}